# Generated by Django 5.0.7 on 2025-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Vendor', 'Vendor')], max_length=30, null=True),
        ),
    ]
